import packageJson from '../../../package.json';
export const VERSION = packageJson.version;
export const COUNT_TASK = [3, 5];

export const SETTINGS_NEW_TODO_CONFIRM = false;
export const SETTINGS_EDIT_TODO_CONFIRM = false;
export const SETTINGS_DELETE_TODO_CONFIRM = false;
export const SETTINGS_TASK_DELETE_CONFIRM = false;
export const SETTINGS_TASK_EDIT_CONFIRM = false;
export const SETTINGS_TASK_CHECK_CONFIRM = false;
export const SETTINGS_NEW_TASK_CONFIRM = false;

export const TODO_NEW_DIALOG = 'TODO_NEW_DIALOG';
export const TODO_NEW_PARTIAL_SAVE = 'TODO_NEW_PARTIAL_SAVE';
export const TODO_NEW_CANCEL = 'TODO_NEW_CANCEL';
export const TODO_NEW_SUBMIT = 'TODO_NEW_SUBMIT';
export const TODO_NEW_CONFIRM_CANCEL = 'TODO_NEW_CONFIRM_CANCEL';
export const TODO_NEW_CONFIRM_SUBMIT = 'TODO_NEW_CONFIRM_SUBMIT';

export const TASK_VISIBLE = 'TASK_VISIBLE';

export const TODO_DETAILS = 'TODO_DETAILS';

export const TODO_DELETE_SUBMIT = 'TODO_DELETE_SUBMIT';
export const TODO_DELETE_CONFIRM_SUBMIT = 'TODO_DELETE_CONFIRM_SUBMIT';
export const TODO_DELETE_CONFIRM_CANCEL = 'TODO_DELETE_CONFIRM_CANCEL';

export const TODO_EDIT_NAME_DIALOG = 'TODO_EDIT_NAME_DIALOG';
export const TODO_EDIT_NAME_CANCEL = 'TODO_EDIT_NAME_CANCEL';
export const TODO_EDIT_NAME_SUBMIT = 'TODO_EDIT_NAME_SUBMIT';
export const TODO_EDIT_NAME_PARTIAL_SAVE = 'TODO_EDIT_NAME_PARTIAL_SAVE';
export const TODO_EDIT_NAME_CONFIRM_CANCEL = 'TODO_EDIT_NAME_CONFIRM_CANCEL';
export const TODO_EDIT_NAME_CONFIRM_SUBMIT = 'TODO_EDIT_NAME_CONFIRM_SUBMIT';

export const TASK_DELETE_SUBMIT = 'TASK_DELETE_SUBMIT';
export const TASK_DELETE_CONFIRM_CANCEL = 'TASK_DELETE_CONFIRM_CANCEL';
export const TASK_DELETE_CONFIRM_SUBMIT = 'TASK_DELETE_CONFIRM_SUBMIT';

export const TASK_EDIT_NAME_DIALOG = 'TASK_EDIT_NAME_DIALOG';
export const TASK_EDIT_NAME_CANCEL = 'TASK_EDIT_NAME_CANCEL';
export const TASK_EDIT_NAME_SUBMIT = 'TASK_EDIT_NAME_SUBMIT';
export const TASK_EDIT_NAME_PARTIAL_SAVE = 'TASK_EDIT_NAME_PARTIAL_SAVE';
export const TASK_EDIT_NAME_CONFIRM_CANCEL = 'TASK_EDIT_NAME_CONFIRM_CANCEL';
export const TASK_EDIT_NAME_CONFIRM_SUBMIT = 'TASK_EDIT_NAME_CONFIRM_SUBMIT';

export const TASK_CHECK_SUBMIT = 'TASK_CHECK_SUBMIT';
export const TASK_CHECK_CONFIRM_CANCEL = 'TASK_CHECK_CONFIRM_CANCEL';
export const TASK_CHECK_CONFIRM_SUBMIT = 'TASK_CHECK_CONFIRM_SUBMIT';

export const TASK_NEW_DIALOG = 'TASK_NEW_DIALOG';
export const TASK_NEW_PARTIAL_SAVE = 'TASK_NEW_PARTIAL_SAVE';
export const TASK_NEW_CANCEL = 'TASK_NEW_CANCEL';
export const TASK_NEW_SUBMIT = 'TASK_NEW_SUBMIT';
export const TASK_NEW_CONFIRM_CANCEL = 'TASK_NEW_CONFIRM_CANCEL';
export const TASK_NEW_CONFIRM_SUBMIT = 'TASK_NEW_CONFIRM_SUBMIT';
